name: Build APK
on: [push, workflow_dispatch]
jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g cordova
      - run: |
          cordova create myapp com.example.fincrx FincrxApp
          cd myapp
          cordova platform add android --confirm=false
          
          # HTML फाइल कॉपी करें
          rm -rf www/*
          cp ../fincrx.html www/index.html
          
          # सीधे एंड्रॉइड के सिस्टम फोल्डर (res) में आइकन रिप्लेस करें
          cd platforms/android/app/src/main/res
          find . -name "ic_launcher.png" -exec cp -f ../../../../../../../icon.png {} \;
          cd ../../../../../..
          
          cordova build android --confirm=false
      - name: Find All Android Packages
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: |
            **/*.apk
            **/*.aab
            
